### PR TITLE
Added support for Django 1.9.x

### PR DESCRIPTION
**Pull request by drakej**

### CODE REVIEW

**Comment by RossRogers** [comment]
This won't be sufficient for support, but it is a start.  I'm working on setting up Vagrant with Virtual box and getting a good cross-product compatibility suite running:

![Alt text](http://g.gravizo.com/g?
digraph G {
    compound=true; nodesep=0.25; ranksep=1; ordering=in; rankdir=LR;
    subgraph cluster_django {
        label = "Django"; color=black;
        1.6;
        1.7;
        1.8;
        1.9;
    }
    1.6 -> win_2012_client [ltail=cluster_django, lhead=cluster_client_os, label="×"];
    subgraph cluster_client_os {
        label = "Client OS"; color=black;
        ubuntu_client   [label="Ubuntu\\n14.04 x86_64"];
        win_7_client    [label="Win 7 Pro\\n x64 SP1"];
        win_10_client   [label="Win 10"];
        win_2008_client [label="Win 2008\\nR2 Standard"];
        win_2012_client [label="Win 2012\\nR2 Standard"];
    }
    win_2012_client -> win_7_db_srvr [ltail=cluster_client_os, lhead=cluster_db_host_os, label="×"];
    subgraph cluster_db_host_os {
        label = "DB Host OS"; color=black;
        subgraph cluster_win_db_host_os {
            label = "Windows DB Host OS"; color=black;
            win_7_db_srvr    [label="Win 7 Pro\\n x64 SP1"];
            win_10_db_srvr   [label="Win 10"];
            win_2008_db_srvr [label="Win 2008\\nR2 Standard"];
            win_2012_db_srvr [label="Win 2012\\nR2 Standard"];
        }
        subgraph cluster_as400_db_host_os {
            label = "IBM DB Host OS"; color=black;
            as400_db_srvr [label="AS/400"];
        }
    }
    win_7_db_srvr -> sql_express_2000[ltail=cluster_win_db_host_os, lhead=cluster_windows_dbs, label="×"];
    as400_db_srvr -> DB2[ltail=cluster_as400_db_host_os, lhead=cluster_ibm_dbs, label="×"];
    subgraph cluster_db {
        label="DBs"; color=black;
        subgraph cluster_windows_dbs {
            label="Microsoft Hosted\\nSQL Server"; color=black;
            sql_express_2000    [label="Express\\n2000"];
            sql_express_2005    [label="Express\\n2005"];
            sql_express_2008_r2 [label="Express\\n2008 R2"];
            sql_express_2012    [label="Express\\n2012"];
            sql_express_2014    [label="Express\\n2014"];
        }
        subgraph cluster_ibm_dbs {
            label="IBM Hosted DBs"; color=black;
            DB2;
        }
    }
})

No firm ETA on this.

I think this edit can be pulled in but it doesn't guarantee full support.  Dan @dlo ?

**Comment by dlo** [comment]
Wow, that's awesome Ross! I don't see much of a downside to merging. If anyone sees issues, we can always address as needed.

**Comment by drakej** [comment]
Agreed. I only added this to help get the ball rolling. I've ran a few stored procedure calls through the driver with the change and haven't seen any issues, but that's only the tip of the iceberg and I don't claim any responsibility for any other broken functionality. That's for the unit tests ;)

**Comment by dlo** [comment]
Thanks @drakej!

**Pull request merged**
