### PR TITLE
FIX: TableInfo for inspectdb introduced in PR #108

### PR DESCRIPTION
**Pull request by davejcameron**
Introduced in PR #108 where the TableInfo object was not imported

### CODE REVIEW

**Comment by RossRogers** [comment]
This merge broken Django 1.7 integration.  `TableInfo` does not exist in Django 1.7.  I know I'm on an outdated version of Django and I need to update, but it is a bummer to see backwards incompatible edits.

@dlo

**Comment by dlo** [comment]
@RossRogers I guess there's never a bad time to discuss a deprecation / end-of-life plan for older Django versions. For the time being can you pin the version to 0.4.3 or earlier? Not many new features have been added yet so I don't think you'd be missing out on much.

**Comment by davejcameron** [comment]
@RossRogers @dlo I was thinking of setting up Travis CI tonight to do simple compatibility tests against Django versions and Python versions you're planning on supporting. That would have caught this on the PR. Thoughts?

**Comment by RossRogers** [comment]
**Dan**,

We need to deprecate when we hit a significant road block, not when someone doesn't even check if a class exists in an older version of Django.  If you look at the code base, you and others have scrupulously maintained backwards compatibility for years.  I personally use django-pyodbc to talk to antique IBM systems that should have died in the 80s and other internal Microsoft SQL Server instances provided by external vendors pinned to version 2000 of Microsoft SQL Server.  Providing an awesome, consistent django veneer on all these products is very commendable.  I don't think we should drop support flippantly.

Shame on me for being out of date.  The trouble is I have other dependencies that also broke backwards compatibility, so I'm in dependency hell, stuck on Django 1.7, until I can get some time to migrate my code base.  Speaking of dependency hell, I think we should be using [semantic versioning](http://semver.org/) to bandaid the symptoms of dependency hell. This is a pretty stable library and we should guarantee users that we're not breaking backwards compatibility, or we'll update the major version number, per sem-ver.  e.g. version `0.4.3` was 1.x.y and `0.4.4` would be `2.0.0`, because it broke backwards compatibility.

**Dave**,
A Travis CI would be awesome just to test against all supported versions of Django.  How do you propose testing against different Microsoft SQL Server versions?

**Comment by dlo** [comment]
@RossRogers Many good points. Ultimately, if I had known that this merge would break compatibility I would not have merged as provided. I think a migration to semver is a fantastic idea. I'm going to fix the error introduced in this PR and will then push as `1.0.0`. No time better than the present.

I've always hesitated to move to the 1.0 mark as it's so hard to know if (or what) bugs might be lurking below the surface, but enough people have been running django-pyodbc in production by now that any huge bugs would have made themselves known by now.

There is no shame in running out-of-date versions; the shame is really on me for merging without realizing there was a backwards-incompatible import.

@davejcameron I fully support additions to test all supported Django versions; at the very least, we should check whether the code runs under each version. If you would submit a PR that would be greatly appreciated.

Supporting various MS SQL Server versions seems like it'd be a much harder endeavor (not sure if that's possible on Travis?).

**Comment by davejcameron** [comment]
@RossRogers and @dlo I'm going to play with AppVeyor it looks like it already has a bunch of SQL Server versions that can be used to test against.

https://www.appveyor.com/docs/services-databases/

I'll give it a go and see how far I can get.

**Comment by dlo** [comment]
@RossRogers Just made a few tweaks to the PR. Can you check master to see it fixes the issue?

**Comment by RossRogers** [comment]
**Dan**,

Thanks for the work on the compatibility front.  I understand the fatigue of maintenance that you're experiencing, but I really appreciate all the work you already done.

I was going down that path you took, but now it is complaining about `compile` not taking 3 arguments.  Anyways, I'll look into it at work tomorrow.  I didn't have the IQ or the will to tackle the problem on Friday at 3pm.

**Dave**,
Nice!  I was looking into [vagrant](https://www.vagrantup.com/) at one point, but I couldn't figure out how to get ssh working on the virtualbox and then life interrupted me.  Your path looks promising!

**Comment by davejcameron** [comment]
@RossRogers @dlo looks like I'm getting somewhere on the CI side of things. Take a look here and you'll see that the tests for Django 1.5.11 are currently running. https://ci.appveyor.com/project/davejcameron/django-pyodbc

**Comment by davejcameron** [comment]
**Dan**,

I have CI working for Python 2.7 32-bit, with SQL 2008 testing Django 1.5 - 1.10. There appears to be some issues with the Django 1.5 tests as well as with the test runner script for the rest of the Django versions. How do you want to handle the CI work? There could be separation between "getting CI configured" vs. getting all the tests and test runner script to work (which I could use some help with)

See: https://ci.appveyor.com/project/davejcameron/django-pyodbc build appveyor-27

**Comment by RossRogers** [comment]
David,

Do you have quick notes for how I could run [my latest pull request](https://github.com/lionheart/django-pyodbc/pull/125) against that system?

**Comment by davejcameron** [comment]
Ross - 

The Django 1.7 test-runner doesn't work correctly (but should hopefully be a trivial change that you can test locally.) 

You could make a fork off this branch here: 
https://github.com/davejcameron/django-pyodbc/tree/appveyor

And then just sign up for appveyor with your github account. You shouldn't require anything else to get it to work with AppVeyor.

**Comment by davejcameron** [comment]
Ross - 

Looks like you've got what I have working now. I was trying to get SQL Server set up locally so I could work on the test runner for Django 1.7 but probably won't have time for a couple of days to do that. Let me know if you make any progress.

**Comment by RossRogers** [comment]
Yup, it's doing its thing.  I'll pick away at it as time affords.  Thanks for settings this up.

**Pull request merged**
