### PR TITLE
Support Django 1.11

### PR DESCRIPTION
**Pull request by jallen1788**
This is probably not complete, but it worked for my limited scope and may be a start.

Please send any advice and I might be able to more fully implement.

### CODE REVIEW

**Comment by dlo** [comment]
thank you @jallen1788! this looks great, only needs tests and then I think we'd be good to go.

**Comment by gone** [comment]
Anything I do to help move this along?

**Comment by RossRogers** [comment]
Well, I was actively working on releasing a Django 2.0-compatible alpha
release when I got this email.  Pypi is a pain.

**Comment by RossRogers** [comment]
Hi Jared,

I just released alpha version 2.0.0a1.  This is based on me getting the
system to work for my codebase and we don't have other code coverage yet..
In order to get this release, please do pip install
django-pyodbc==2.0.0a1.

See my commit message for more details:
https://github.com/lionheart/django-pyodbc/commit/f510afd69be15ea18593ae6b4b14e0386eafa758

 - Ross

**Comment by RossRogers** [comment]
Jared,

I have done basically the same [edits as you here](https://github.com/lionheart/django-pyodbc/commit/f510afd69be15ea18593ae6b4b14e0386eafa758) in support of Django 2.0 and released it as 2.0.0a1 on pip.  Apologies for re-inventing the wheel, but I am going to close this pull request at this time.  Please feel-free to re-open and comment on this ticket if I have misstepped.

**Comment by jallen1788** [comment]
Good with me. Sorry, I haven't had time to clean this up, and wasn't very confident in the coverage of my solution. Yours looks much better.

**Comment by RossRogers** [comment]
Great!

**Pull request closed without merging**
