### PR TITLE
Pass extra args to SQLCompiler.as_sql() in django 1.8-1.10 (fixes exc…

### PR DESCRIPTION
**Pull request by benmehlman**
…eption when doing subquery)

Patch for issue described in https://github.com/lionheart/django-pyodbc/issues/143, this should fix the issue operating with django 1.8-1.10 but retain both backward and forward compatibility.

Note: the reason for cancellation of the first pull request and creation of this one is because I had pushed my commit to master rather than creating an issue-specific branch, and immediately regretted it...  So now I've moved it to its own branch which I hope will be easier for you.

Thanks!
Ben Mehlman

### CODE REVIEW

**Comment by benmehlman** [comment]
Thanks but it seems useless now, because I can't seem to find any commit of django-pyodbc that works with django 1.11 now.  I've been using my fork of django-pyodbc (with my patches) w/ django1.10, now I am trying to get to 1.11 as a stepping stone to eventually going to 2+.. and what I see is that someone else wrote some fixes to make django-pyodbc work with 1.11 on top of the ones I did to make it work with 1.10.. but before those patches were merged, support for anything less than django 2.0 was dropped???  So I have to go back to my fork and fix it for 1.11 :(

**Comment by RossRogers** [comment]
Unfortunately, Django upgrades are pretty painful in general.  Why do you think you need to step through 1.11 instead of jumping straight to Django 2+?

**Comment by benmehlman** [comment]
.. because I'm one developer supporting a commercial production environment with years worth of custom code, and I can't afford to break 100 things at once.  This system manages orders, customers, it prints all our checks, it does our payroll....   Changing from Python2 / Django1 to Python3 / Django 2 with all the third party library upgrades that would go with that, as well as all the changes to my own code and libraries, could cause breakage that might not be discovered until major business problems come up.  So it's more prudent to do it in stages.

But I'm just saying, the patches exist to make django-pyodbc work with django 1.10 and 1.11 it seems they were just applied in the wrong order so that the patch that eliminates 1.x support was applied first????

**Comment by RossRogers** [comment]
Okey doke.  You're describing my exact situation and I chose to jump to Django 2 and Python 3 because every upgrade in Django is pain and the magnitude of the pain of any single Django upgrade is not mitigated by incremental upgrades, in my opinion.

**Comment by benmehlman** [comment]
Well.. it is not what I want to do, but I can either do that or go back to my fork for 1.10 and cherry pick the patches someone submitted for 1.11.  I'm perplexed that you don't seem to understand that my patches were for 1.10 and you merged them after a patch that removes support for <2 thereby leaving 1.10 and 1.11 users in a lurch when you didn't have to??  It happens, I get it.. but this seeming blank wall approach confuses me.  Anyway I am trying django-pyodbc-azure 1.11.15 with Django 1.11 and so far so good, this might all work out ok....

**Comment by RossRogers** [comment]
I see what you're saying, I'm just trying to help you find a workaround.  I'm in the middle of harvest at my company and I personally won't be able to devote time to this other than this discussion at the moment.  Anyways, I'll let others chime in.

**Pull request merged**
